# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning about Speech Recognition and Machine Learning
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD student in linguistics at the University of Arizona, working on automatic speech recognition. This blog is some of what I'm learning along the way.

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: sladkoezhnik
github_username:  JRMeyer

# Build settings
markdown: kramdown

# use pygments over rouge
highlighter: pygments
